# Tuesday Exercises

a)  

```{r}
reactions <- read.table(file = "T10_1_CHEM.DAT", sep = "")
reactions
```

```{r}
names(reactions) <- c("Obs", "PercUnchanged", "PercConvert", "PercUnwant", "Temp", "Conc", "Time")
reactions
```

b)  

```{r}
reactions.lm <- lm(PercUnwant ~ Temp + Conc + Time, data = reactions)
summary(reactions.lm)
```

c)  From the R output it seems that the R-squared statistic is 0.7163, which means that 71.63% of the variation in Percent Unwanted can be explained by the linear model using Time, Concentration, and Temperature.

# Thursday Exercises

a)  

```{r}
testMatrix <- matrix(c(1,2,3,
                       4,5,6,
                       7,8,9), byrow=T, nrow=3)
testMatrix
```

```{r}
testVector <- matrix(c(10,11,12), byrow=T, ncol=1)
testVector
t(testVector)
```

b)  

```{r}
A <- matrix(c(4,2,3,
              7,5,8), byrow =T, nrow = 2)
B <- matrix(c(3,-2,4,
              6,9,-5), byrow =T, nrow = 2)
A+B
A-B
t(A)%*%A
A%*%t(A)
```

c)  

```{r}
A <- matrix(c(1,-1,4,
              -1,1,3,
              4,3,2), byrow =T, nrow = 3)
B <- matrix(c(3,-2,4,
              7,1,0,
              2,3,5), byrow =T, nrow = 3)
x <- matrix(c(1,-1,2), byrow =T, ncol = 1)
y <- matrix(c(3,2,1), byrow =T, ncol = 1)

#a
B%*%x
#b
t(y)%*%B
#c - scalar quadratic form
t(x)%*%A%*%x
#d
t(x)%*%A%*%y
#e
t(x)%*%x
#f
t(x)%*%y
#g
x%*%t(x)
#h
x%*%t(y)
#i
t(B)%*%B
```

d)  

```{r}
A <- matrix(c(1,1,-2,
              -1,2,1,
              0,1,-1), byrow =T, nrow = 3)
eigen_vec_values <- eigen(A)
eigen_vec_values
```

```{r}
det(A)
```

The determinant is related to the eigenvalues for this square matrix as it is the product of the eigenvalues.
